// Standalone recovery script: (re)sets the admin PIN without touching any other
// data (inventory, invoices, staff). Useful when the PIN generated by `seed:fresh`
// gets lost, or to set a known starting PIN. Unlike `seed`/`seed:fresh`, this never
// deletes anything.
const authModel = require('../models/auth.model');

const pin = process.argv[2] || '1234';

if (!/^\d{4,6}$/.test(pin)) {
  console.error('El PIN debe tener entre 4 y 6 dígitos.');
  process.exit(1);
}

authModel.setAdminPin(pin);
console.log(`PIN de administrador actualizado a: ${pin}`);
console.log('Cámbialo cuanto antes desde el Panel de Administración si es un valor conocido/fácil de adivinar como 1234.');
